# Generated by Django 3.1.3 on 2020-11-24 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taskapi.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draggable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DragandDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', taskapi.fields.OrderField(blank=True, unique=True)),
                ('draggable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_of_draggable', to='taskapi.draggable')),
            ],
        ),
        migrations.CreateModel(
            name='AddingColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backround', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draganddrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='taskapi.draganddrop')),
            ],
        ),
    ]
